RECEIVER_EMAIL = 'valiahmetov.farit@gmail.com'
EMAIL_SUBJECT = 'Тестовое задание. Долгоаршинных.'
EMAIL_TEXT = 'Найдено {} писем'
LOGIN = 'avsenov.nikolay@gmail.com'
PASSWORD = '123456'
LOGIN_URL = 'http://gmail.com'
HUB = 'http://192.168.88.238:4444/wd/hub'
